version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
#      - wpdocker_db:/var/lib/mysql
      - ./localdb:/var/lib/mysql
      - ./db:/tmp/backups
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpdocker
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8088:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wpdocker
    volumes:
      - ./wordpress/wp-content/:/var/www/html/wp-content
      
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      MYSQL_USERNAME: user
      MYSQL_ROOT_PASSWORD: password
    
volumes:
  wpdocker_db: {}