version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - wpdocker_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpdocker
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wpdocker
    volumes:
      - ./wordpress/wp-content/:/var/www/html/wp-content
volumes:
  wpdocker_db: {}